// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using UTC_DATN.Entities;

namespace UTC_DATN.Data;

public partial class UTC_DATNContext : DbContext
{
    public UTC_DATNContext(DbContextOptions<UTC_DATNContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AntiCheatEvent> AntiCheatEvents { get; set; }

    public virtual DbSet<Application> Applications { get; set; }

    public virtual DbSet<ApplicationAiScore> ApplicationAiScores { get; set; }

    public virtual DbSet<ApplicationNote> ApplicationNotes { get; set; }

    public virtual DbSet<ApplicationStageHistory> ApplicationStageHistories { get; set; }

    public virtual DbSet<Assessment> Assessments { get; set; }

    public virtual DbSet<AssessmentAnswer> AssessmentAnswers { get; set; }

    public virtual DbSet<AssessmentAttempt> AssessmentAttempts { get; set; }

    public virtual DbSet<AssessmentInvite> AssessmentInvites { get; set; }

    public virtual DbSet<AssessmentQuestion> AssessmentQuestions { get; set; }

    public virtual DbSet<AutomationRule> AutomationRules { get; set; }

    public virtual DbSet<Candidate> Candidates { get; set; }

    public virtual DbSet<CandidateDocument> CandidateDocuments { get; set; }

    public virtual DbSet<CandidateEducation> CandidateEducations { get; set; }

    public virtual DbSet<CandidateExperience> CandidateExperiences { get; set; }

    public virtual DbSet<CandidateSkill> CandidateSkills { get; set; }

    public virtual DbSet<ChatMessage> ChatMessages { get; set; }

    public virtual DbSet<ChatSession> ChatSessions { get; set; }

    public virtual DbSet<EmailQueue> EmailQueues { get; set; }

    public virtual DbSet<EmailSendLog> EmailSendLogs { get; set; }

    public virtual DbSet<EmailTemplate> EmailTemplates { get; set; }

    public virtual DbSet<UTC_DATN.Entities.File> Files { get; set; }

    public virtual DbSet<Interview> Interviews { get; set; }

    public virtual DbSet<InterviewFeedback> InterviewFeedbacks { get; set; }

    public virtual DbSet<InterviewScorecard> InterviewScorecards { get; set; }

    public virtual DbSet<Interviewer> Interviewers { get; set; }

    public virtual DbSet<InterviewEvaluation> InterviewEvaluations { get; set; }

    public virtual DbSet<Job> Jobs { get; set; }

    public virtual DbSet<JobSkillMap> JobSkillMaps { get; set; }

    public virtual DbSet<JobTag> JobTags { get; set; }

    public virtual DbSet<PipelineStage> PipelineStages { get; set; }

    public virtual DbSet<PreScreenAnswer> PreScreenAnswers { get; set; }

    public virtual DbSet<PreScreenQuestion> PreScreenQuestions { get; set; }

    public virtual DbSet<QuestionBank> QuestionBanks { get; set; }

    public virtual DbSet<QuestionOption> QuestionOptions { get; set; }

    public virtual DbSet<RefreshToken> RefreshTokens { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<Skill> Skills { get; set; }

    public virtual DbSet<JobType> JobTypes { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserRole> UserRoles { get; set; }

    public virtual DbSet<NotificationSetting> NotificationSettings { get; set; }
    public virtual DbSet<Notification> Notifications { get; set; }
    public virtual DbSet<SavedJob> SavedJobs { get; set; }
    public virtual DbSet<CoverLetter> CoverLetters { get; set; }
    public virtual DbSet<ApplicationView> ApplicationViews { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<CoverLetter>(entity =>
        {
            entity.HasKey(e => e.CoverLetterId);
            entity.Property(e => e.CoverLetterId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.Title).IsRequired().HasMaxLength(200);
            entity.Property(e => e.Content).IsRequired();
            entity.Property(e => e.IsDefault).HasDefaultValue(false);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.HasOne(d => d.Candidate).WithMany()
                .HasForeignKey(d => d.CandidateId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_CoverLetters_Candidates");
        });

        modelBuilder.Entity<SavedJob>(entity =>
        {
            entity.HasKey(e => e.SavedJobId);

            entity.HasIndex(e => new { e.CandidateId, e.JobId }, "UQ_SavedJobs_Candidate_Job").IsUnique();

            entity.Property(e => e.SavedJobId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.SavedAt).HasDefaultValueSql("(sysutcdatetime())");

            entity.HasOne(d => d.Candidate).WithMany()
                .HasForeignKey(d => d.CandidateId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_SavedJobs_Candidates");

            entity.HasOne(d => d.Job).WithMany()
                .HasForeignKey(d => d.JobId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_SavedJobs_Jobs");
        });
        modelBuilder.Entity<Notification>(entity =>
        {
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.Title).IsRequired().HasMaxLength(200);
            entity.Property(e => e.Type).IsRequired().HasMaxLength(50);
            entity.Property(e => e.IsRead).HasDefaultValue(false);

            entity.HasOne(d => d.User).WithMany()
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_Notifications_Users");
        });
        modelBuilder.Entity<AntiCheatEvent>(entity =>
        {
            entity.HasIndex(e => e.AttemptId, "IX_AntiCheatEvents_AttemptId");

            entity.Property(e => e.AntiCheatEventId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.EventAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.EventType)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.Attempt).WithMany(p => p.AntiCheatEvents)
                .HasForeignKey(d => d.AttemptId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AntiCheatEvents_Attempt");
        });

        modelBuilder.Entity<Application>(entity =>
        {
            entity.HasIndex(e => e.CandidateId, "IX_Applications_CandidateId");

            entity.HasIndex(e => e.JobId, "IX_Applications_JobId");

            entity.HasIndex(e => new { e.JobId, e.CandidateId }, "UQ_Applications_Job_Candidate").IsUnique();

            entity.Property(e => e.ApplicationId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.AppliedAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.LastStageChangedAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.Source).HasMaxLength(100);
            entity.Property(e => e.LastViewedAt).HasColumnType("datetime2");
            entity.Property(e => e.LastViewedBy).HasColumnName("LastViewedBy");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(30)
                .HasDefaultValue("ACTIVE");

            entity.HasOne(d => d.Candidate).WithMany(p => p.Applications)
                .HasForeignKey(d => d.CandidateId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Applications_Candidates");

            entity.HasOne(d => d.CurrentStage).WithMany(p => p.Applications)
                .HasForeignKey(d => d.CurrentStageId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Applications_Stage");

            entity.HasOne(d => d.Job).WithMany(p => p.Applications)
                .HasForeignKey(d => d.JobId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Applications_Jobs");

            entity.HasOne(d => d.ResumeDocument).WithMany(p => p.Applications)
                .HasForeignKey(d => d.ResumeDocumentId)
                .HasConstraintName("FK_Applications_ResumeDoc");
        });

        modelBuilder.Entity<ApplicationAiScore>(entity =>
        {
            entity.HasKey(e => e.AiScoreId);

            entity.HasIndex(e => e.ApplicationId, "IX_AiScores_AppId");

            entity.Property(e => e.AiScoreId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.MatchingScore).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.Model).HasMaxLength(50);

            entity.HasOne(d => d.Application).WithMany(p => p.ApplicationAiScores)
                .HasForeignKey(d => d.ApplicationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ApplicationAiScores_App");
        });

        modelBuilder.Entity<ApplicationNote>(entity =>
        {
            entity.HasKey(e => e.NoteId);

            entity.HasIndex(e => e.ApplicationId, "IX_ApplicationNotes_AppId");

            entity.Property(e => e.NoteId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.Note).IsRequired();

            entity.HasOne(d => d.Application).WithMany(p => p.ApplicationNotes)
                .HasForeignKey(d => d.ApplicationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ApplicationNotes_App");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.ApplicationNotes)
                .HasForeignKey(d => d.CreatedBy)
                .HasConstraintName("FK_ApplicationNotes_User");
        });

        modelBuilder.Entity<ApplicationStageHistory>(entity =>
        {
            entity.HasKey(e => e.HistoryId);

            entity.ToTable("ApplicationStageHistory");

            entity.HasIndex(e => e.ApplicationId, "IX_StageHistory_AppId");

            entity.Property(e => e.HistoryId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.ChangedAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.Reason).HasMaxLength(500);

            entity.HasOne(d => d.Application).WithMany(p => p.ApplicationStageHistories)
                .HasForeignKey(d => d.ApplicationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_StageHistory_App");

            entity.HasOne(d => d.ChangedByNavigation).WithMany(p => p.ApplicationStageHistories)
                .HasForeignKey(d => d.ChangedBy)
                .HasConstraintName("FK_StageHistory_User");

            entity.HasOne(d => d.FromStage).WithMany(p => p.ApplicationStageHistoryFromStages)
                .HasForeignKey(d => d.FromStageId)
                .HasConstraintName("FK_StageHistory_From");

            entity.HasOne(d => d.ToStage).WithMany(p => p.ApplicationStageHistoryToStages)
                .HasForeignKey(d => d.ToStageId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_StageHistory_To");
        });

        modelBuilder.Entity<Assessment>(entity =>
        {
            entity.Property(e => e.AssessmentId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.DurationMinutes).HasDefaultValue(30);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Mode)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("FIXED");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.PassScore)
                .HasDefaultValue(60m)
                .HasColumnType("decimal(5, 2)");
            entity.Property(e => e.RandomTags).HasMaxLength(300);
            entity.Property(e => e.ShowResultToCandidate).HasDefaultValue(true);

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.Assessments)
                .HasForeignKey(d => d.CreatedBy)
                .HasConstraintName("FK_Assessments_User");
        });

        modelBuilder.Entity<AssessmentAnswer>(entity =>
        {
            entity.HasKey(e => e.AnswerId);

            entity.HasIndex(e => e.AttemptId, "IX_AssessmentAnswers_AttemptId");

            entity.Property(e => e.AnswerId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.PointsEarned).HasColumnType("decimal(6, 2)");

            entity.HasOne(d => d.Attempt).WithMany(p => p.AssessmentAnswers)
                .HasForeignKey(d => d.AttemptId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AssessmentAnswers_Attempt");

            entity.HasOne(d => d.BankQuestion).WithMany(p => p.AssessmentAnswers)
                .HasForeignKey(d => d.BankQuestionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AssessmentAnswers_Q");
        });

        modelBuilder.Entity<AssessmentAttempt>(entity =>
        {
            entity.HasKey(e => e.AttemptId);

            entity.HasIndex(e => e.InviteId, "IX_AssessmentAttempts_InviteId");

            entity.Property(e => e.AttemptId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.CandidateIp).HasMaxLength(100);
            entity.Property(e => e.Score).HasColumnType("decimal(7, 2)");
            entity.Property(e => e.StartedAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("IN_PROGRESS");
            entity.Property(e => e.UserAgent).HasMaxLength(500);

            entity.HasOne(d => d.Invite).WithMany(p => p.AssessmentAttempts)
                .HasForeignKey(d => d.InviteId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AssessmentAttempts_Invite");
        });

        modelBuilder.Entity<AssessmentInvite>(entity =>
        {
            entity.HasKey(e => e.InviteId);

            entity.HasIndex(e => e.ApplicationId, "IX_AssessmentInvites_AppId");

            entity.HasIndex(e => e.Code, "UQ_AssessmentInvites_Code").IsUnique();

            entity.Property(e => e.InviteId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.SentToEmail).HasMaxLength(320);

            entity.HasOne(d => d.Application).WithMany(p => p.AssessmentInvites)
                .HasForeignKey(d => d.ApplicationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AssessmentInvites_App");

            entity.HasOne(d => d.Assessment).WithMany(p => p.AssessmentInvites)
                .HasForeignKey(d => d.AssessmentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AssessmentInvites_Assessment");
        });

        modelBuilder.Entity<AssessmentQuestion>(entity =>
        {
            entity.HasKey(e => new { e.AssessmentId, e.BankQuestionId });

            entity.Property(e => e.Points)
                .HasDefaultValue(1m)
                .HasColumnType("decimal(6, 2)");

            entity.HasOne(d => d.Assessment).WithMany(p => p.AssessmentQuestions)
                .HasForeignKey(d => d.AssessmentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AssessmentQuestions_A");

            entity.HasOne(d => d.BankQuestion).WithMany(p => p.AssessmentQuestions)
                .HasForeignKey(d => d.BankQuestionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AssessmentQuestions_Q");
        });

        modelBuilder.Entity<AutomationRule>(entity =>
        {
            entity.HasKey(e => e.RuleId);

            entity.Property(e => e.RuleId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.TriggerEvent)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.Template).WithMany(p => p.AutomationRules)
                .HasForeignKey(d => d.TemplateId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AutomationRules_Template");
        });

        modelBuilder.Entity<Candidate>(entity =>
        {
            entity.HasIndex(e => e.NormalizedEmail, "IX_Candidates_NormalizedEmail");

            entity.Property(e => e.CandidateId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.Email).HasMaxLength(320);
            entity.Property(e => e.FullName).HasMaxLength(200);
            entity.Property(e => e.Headline).HasMaxLength(300);
            entity.Property(e => e.Location).HasMaxLength(200);
            entity.Property(e => e.NormalizedEmail)
                .HasMaxLength(320)
                .HasComputedColumnSql("(upper(ltrim(rtrim([Email]))))", true);
            entity.Property(e => e.Phone).HasMaxLength(50);
            entity.Property(e => e.Source).HasMaxLength(100);
        });

        modelBuilder.Entity<CandidateDocument>(entity =>
        {
            entity.HasIndex(e => e.CandidateId, "IX_CandidateDocuments_CandidateId");

            entity.Property(e => e.CandidateDocumentId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.DocType)
                .IsRequired()
                .HasMaxLength(30)
                .HasDefaultValue("CV");
            
            entity.Property(e => e.DisplayName).HasMaxLength(255);
            entity.Property(e => e.IsPrimary).HasDefaultValue(false);

            entity.HasOne(d => d.Candidate).WithMany(p => p.CandidateDocuments)
                .HasForeignKey(d => d.CandidateId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CandidateDocuments_Candidates");

            entity.HasOne(d => d.File).WithMany(p => p.CandidateDocuments)
                .HasForeignKey(d => d.FileId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CandidateDocuments_Files");
        });

        modelBuilder.Entity<CandidateEducation>(entity =>
        {
            entity.HasKey(e => e.EducationId);

            entity.HasIndex(e => e.CandidateId, "IX_CandidateEducations_CandidateId");

            entity.Property(e => e.EducationId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.Degree).HasMaxLength(200);
            entity.Property(e => e.Field).HasMaxLength(200);
            entity.Property(e => e.School).HasMaxLength(200);

            entity.HasOne(d => d.Candidate).WithMany(p => p.CandidateEducations)
                .HasForeignKey(d => d.CandidateId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CandidateEducations_Candidates");
        });

        modelBuilder.Entity<CandidateExperience>(entity =>
        {
            entity.HasKey(e => e.ExperienceId);

            entity.HasIndex(e => e.CandidateId, "IX_CandidateExperiences_CandidateId");

            entity.Property(e => e.ExperienceId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.Company).HasMaxLength(200);
            entity.Property(e => e.Title).HasMaxLength(200);

            entity.HasOne(d => d.Candidate).WithMany(p => p.CandidateExperiences)
                .HasForeignKey(d => d.CandidateId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CandidateExperiences_Candidates");
        });

        modelBuilder.Entity<CandidateSkill>(entity =>
        {
            entity.HasKey(e => new { e.CandidateId, e.SkillId });

            entity.Property(e => e.Years).HasColumnType("decimal(4, 1)");

            entity.HasOne(d => d.Candidate).WithMany(p => p.CandidateSkills)
                .HasForeignKey(d => d.CandidateId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CandidateSkills_Candidates");

            entity.HasOne(d => d.Skill).WithMany(p => p.CandidateSkills)
                .HasForeignKey(d => d.SkillId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CandidateSkills_Skills");
        });

        modelBuilder.Entity<ChatMessage>(entity =>
        {
            entity.HasIndex(e => e.ChatSessionId, "IX_ChatMessages_SessionId");

            entity.Property(e => e.ChatMessageId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.Message).IsRequired();
            entity.Property(e => e.Sender)
                .IsRequired()
                .HasMaxLength(20);

            entity.HasOne(d => d.ChatSession).WithMany(p => p.ChatMessages)
                .HasForeignKey(d => d.ChatSessionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ChatMessages_Session");
        });

        modelBuilder.Entity<ChatSession>(entity =>
        {
            entity.HasIndex(e => e.ApplicationId, "IX_ChatSessions_AppId");

            entity.Property(e => e.ChatSessionId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.Channel)
                .IsRequired()
                .HasMaxLength(30)
                .HasDefaultValue("CAREER_SITE");
            entity.Property(e => e.StartedAt).HasDefaultValueSql("(sysutcdatetime())");

            entity.HasOne(d => d.Application).WithMany(p => p.ChatSessions)
                .HasForeignKey(d => d.ApplicationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ChatSessions_App");
        });

        modelBuilder.Entity<EmailQueue>(entity =>
        {
            entity.ToTable("EmailQueue");

            entity.HasIndex(e => e.ScheduledAt, "IX_EmailQueue_ScheduledAt");

            entity.HasIndex(e => e.Status, "IX_EmailQueue_Status");

            entity.Property(e => e.EmailQueueId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.BodyHtml).IsRequired();
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.FailReason).HasMaxLength(1000);
            entity.Property(e => e.RelatedType).HasMaxLength(50);
            entity.Property(e => e.ScheduledAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(30)
                .HasDefaultValue("QUEUED");
            entity.Property(e => e.Subject)
                .IsRequired()
                .HasMaxLength(300);
            entity.Property(e => e.ToEmail)
                .IsRequired()
                .HasMaxLength(320);
            entity.Property(e => e.ToName).HasMaxLength(200);
        });

        modelBuilder.Entity<EmailSendLog>(entity =>
        {
            entity.ToTable("EmailSendLog");

            entity.HasIndex(e => e.EmailQueueId, "IX_EmailSendLog_QueueId");

            entity.Property(e => e.EmailSendLogId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.Provider)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("SMTP");
            entity.Property(e => e.ProviderMessageId).HasMaxLength(200);
            entity.Property(e => e.Result)
                .IsRequired()
                .HasMaxLength(30);

            entity.HasOne(d => d.EmailQueue).WithMany(p => p.EmailSendLogs)
                .HasForeignKey(d => d.EmailQueueId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_EmailSendLog_Queue");
        });

        modelBuilder.Entity<EmailTemplate>(entity =>
        {
            entity.HasKey(e => e.TemplateId);

            entity.HasIndex(e => e.Code, "UQ_EmailTemplates_Code").IsUnique();

            entity.Property(e => e.TemplateId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.BodyHtml).IsRequired();
            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Subject)
                .IsRequired()
                .HasMaxLength(300);

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.EmailTemplates)
                .HasForeignKey(d => d.CreatedBy)
                .HasConstraintName("FK_EmailTemplates_User");
        });

        modelBuilder.Entity<UTC_DATN.Entities.File>(entity =>
        {
            entity.Property(e => e.FileId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.LocalPath).HasMaxLength(1000);
            entity.Property(e => e.MimeType).HasMaxLength(100);
            entity.Property(e => e.OriginalFileName)
                .IsRequired()
                .HasMaxLength(260);
            entity.Property(e => e.Provider)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("LOCAL");
            entity.Property(e => e.Sha256).HasMaxLength(80);
            entity.Property(e => e.StoredFileName)
                .IsRequired()
                .HasMaxLength(260);
            entity.Property(e => e.Url).HasMaxLength(1000);
        });

        modelBuilder.Entity<Interview>(entity =>
        {
            entity.HasIndex(e => e.ApplicationId, "IX_Interviews_AppId");

            entity.Property(e => e.InterviewId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.Location).HasMaxLength(300);
            entity.Property(e => e.MeetingLink).HasMaxLength(1000);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(30)
                .HasDefaultValue("SCHEDULED");
            entity.Property(e => e.Title).HasMaxLength(200);

            entity.HasOne(d => d.Application).WithMany(p => p.Interviews)
                .HasForeignKey(d => d.ApplicationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Interviews_App");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.Interviews)
                .HasForeignKey(d => d.CreatedBy)
                .HasConstraintName("FK_Interviews_User");
        });

        modelBuilder.Entity<InterviewFeedback>(entity =>
        {
            entity.HasKey(e => e.FeedbackId);

            entity.ToTable("InterviewFeedback");

            entity.HasIndex(e => e.InterviewId, "IX_InterviewFeedback_InterviewId");

            entity.Property(e => e.FeedbackId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.OverallScore).HasColumnType("decimal(6, 2)");
            entity.Property(e => e.Recommendation).HasMaxLength(30);

            entity.HasOne(d => d.Interview).WithMany(p => p.InterviewFeedbacks)
                .HasForeignKey(d => d.InterviewId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_InterviewFeedback_Interview");

            entity.HasOne(d => d.User).WithMany(p => p.InterviewFeedbacks)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_InterviewFeedback_User");
        });

        modelBuilder.Entity<InterviewScorecard>(entity =>
        {
            entity.HasKey(e => e.ScorecardId);

            entity.HasIndex(e => e.InterviewId, "IX_InterviewScorecards_InterviewId");

            entity.Property(e => e.ScorecardId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.CriteriaCode)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CriteriaName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.MaxScore).HasDefaultValue(10);

            entity.HasOne(d => d.Interview).WithMany(p => p.InterviewScorecards)
                .HasForeignKey(d => d.InterviewId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_InterviewScorecards_Interview");
        });

        modelBuilder.Entity<Interviewer>(entity =>
        {
            entity.HasKey(e => new { e.InterviewId, e.UserId });

            entity.Property(e => e.RoleInPanel).HasMaxLength(50);

            entity.HasOne(d => d.Interview).WithMany(p => p.Interviewer)
                .HasForeignKey(d => d.InterviewId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Interviewers_Interview");

            entity.HasOne(d => d.User).WithMany(p => p.Interviewers)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Interviewers_User");
        });

        modelBuilder.Entity<InterviewEvaluation>(entity =>
        {
            entity.HasKey(e => e.EvaluationId);

            entity.HasIndex(e => e.InterviewId, "IX_InterviewEvaluations_InterviewId");

            entity.HasIndex(e => e.InterviewerId, "IX_InterviewEvaluations_InterviewerId");

            entity.Property(e => e.EvaluationId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.Score).IsRequired();
            entity.Property(e => e.Result)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())");

            entity.HasOne(d => d.Interview).WithMany()
                .HasForeignKey(d => d.InterviewId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_InterviewEvaluations_Interview");

            entity.HasOne(d => d.Interviewer).WithMany()
                .HasForeignKey(d => d.InterviewerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_InterviewEvaluations_Interviewer");
        });

        modelBuilder.Entity<Job>(entity =>
        {
            entity.HasIndex(e => e.Status, "IX_Jobs_Status");

            entity.HasIndex(e => e.Title, "IX_Jobs_Title");

            entity.HasIndex(e => e.Code, "UQ_Jobs_Code").IsUnique();

            entity.Property(e => e.JobId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.Currency)
                .HasMaxLength(10)
                .HasDefaultValue("VND");
            entity.Property(e => e.Department).HasMaxLength(200);
            entity.Property(e => e.EmploymentType).HasMaxLength(50);
            entity.Property(e => e.Location).HasMaxLength(200);
            entity.Property(e => e.SalaryMax).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.SalaryMin).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(30)
                .HasDefaultValue("OPEN");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(300);

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.Jobs)
                .HasForeignKey(d => d.CreatedBy)
                .HasConstraintName("FK_Jobs_CreatedBy");

            entity.HasMany(d => d.Tags).WithMany(p => p.Jobs)
                .UsingEntity<Dictionary<string, object>>(
                    "JobTagMap",
                    r => r.HasOne<JobTag>().WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_JobTagMap_Tags"),
                    l => l.HasOne<Job>().WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_JobTagMap_Jobs"),
                    j =>
                    {
                        j.HasKey("JobId", "TagId");
                        j.ToTable("JobTagMap");
                    });
        });

        modelBuilder.Entity<JobSkillMap>(entity =>
        {
            entity.HasKey(e => new { e.JobId, e.SkillId });

            entity.ToTable("JobSkillMap");

            entity.Property(e => e.Weight).HasDefaultValue((byte)1);

            entity.HasOne(d => d.Job).WithMany(p => p.JobSkillMaps)
                .HasForeignKey(d => d.JobId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_JobSkillMap_Jobs");

            entity.HasOne(d => d.Skill).WithMany(p => p.JobSkillMaps)
                .HasForeignKey(d => d.SkillId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_JobSkillMap_Skills");
        });

        modelBuilder.Entity<JobTag>(entity =>
        {
            entity.HasKey(e => e.TagId);

            entity.HasIndex(e => e.NormalizedName, "UQ_JobTags_NormalizedName").IsUnique();

            entity.Property(e => e.TagId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.NormalizedName)
                .HasMaxLength(100)
                .HasComputedColumnSql("(upper(ltrim(rtrim([Name]))))", true);
        });

        modelBuilder.Entity<PipelineStage>(entity =>
        {
            entity.HasKey(e => e.StageId);

            entity.HasIndex(e => e.Code, "UQ_PipelineStages_Code").IsUnique();

            entity.Property(e => e.StageId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(30);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.IsSlaEnabled).HasDefaultValue(false);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.SlaWarnBeforeDays).HasDefaultValue(1);
        });

        modelBuilder.Entity<PreScreenAnswer>(entity =>
        {
            entity.HasKey(e => e.AnswerId);

            entity.HasIndex(e => e.ApplicationId, "IX_PreScreenAnswers_AppId");

            entity.Property(e => e.AnswerId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())");

            entity.HasOne(d => d.Application).WithMany(p => p.PreScreenAnswers)
                .HasForeignKey(d => d.ApplicationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PreScreenAnswers_App");

            entity.HasOne(d => d.Question).WithMany(p => p.PreScreenAnswers)
                .HasForeignKey(d => d.QuestionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PreScreenAnswers_Q");
        });

        modelBuilder.Entity<PreScreenQuestion>(entity =>
        {
            entity.HasKey(e => e.QuestionId);

            entity.HasIndex(e => e.Code, "UQ_PreScreenQuestions_Code").IsUnique();

            entity.Property(e => e.QuestionId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.AnswerType)
                .IsRequired()
                .HasMaxLength(30)
                .HasDefaultValue("TEXT");
            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Question)
                .IsRequired()
                .HasMaxLength(500);
        });

        modelBuilder.Entity<QuestionBank>(entity =>
        {
            entity.HasKey(e => e.BankQuestionId);

            entity.ToTable("QuestionBank");

            entity.Property(e => e.BankQuestionId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.Content).IsRequired();
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.Difficulty).HasMaxLength(20);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Tags).HasMaxLength(300);
            entity.Property(e => e.Type)
                .IsRequired()
                .HasMaxLength(30)
                .HasDefaultValue("MCQ_SINGLE");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.QuestionBanks)
                .HasForeignKey(d => d.CreatedBy)
                .HasConstraintName("FK_QuestionBank_User");
        });

        modelBuilder.Entity<QuestionOption>(entity =>
        {
            entity.HasKey(e => e.OptionId);

            entity.HasIndex(e => e.BankQuestionId, "IX_QuestionOptions_QId");

            entity.Property(e => e.OptionId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.Content)
                .IsRequired()
                .HasMaxLength(1000);

            entity.HasOne(d => d.BankQuestion).WithMany(p => p.QuestionOptions)
                .HasForeignKey(d => d.BankQuestionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_QuestionOptions_Q");
        });

        modelBuilder.Entity<RefreshToken>(entity =>
        {
            entity.HasIndex(e => e.UserId, "IX_RefreshTokens_UserId");

            entity.Property(e => e.RefreshTokenId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.Token)
                .IsRequired()
                .HasMaxLength(500);

            entity.HasOne(d => d.User).WithMany(p => p.RefreshTokens)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RefreshTokens_Users");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasIndex(e => e.Code, "UQ_Roles_Code").IsUnique();

            entity.Property(e => e.RoleId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<Skill>(entity =>
        {
            entity.HasIndex(e => e.NormalizedName, "UQ_Skills_NormalizedName").IsUnique();

            entity.Property(e => e.SkillId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.NormalizedName)
                .HasMaxLength(200)
                .HasComputedColumnSql("(upper(ltrim(rtrim([Name]))))", true);
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasIndex(e => e.NormalizedEmail, "UQ_Users_NormalizedEmail").IsUnique();

            entity.Property(e => e.UserId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(320);
            entity.Property(e => e.FullName).HasMaxLength(200);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.NormalizedEmail)
                .HasMaxLength(320)
                .HasComputedColumnSql("(upper(ltrim(rtrim([Email]))))", true);
            entity.Property(e => e.PasswordHash)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.Phone).HasMaxLength(50);
        });

        modelBuilder.Entity<UserRole>(entity =>
        {
            entity.HasKey(e => new { e.UserId, e.RoleId });

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())");

            entity.HasOne(d => d.Role).WithMany(p => p.UserRoles)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserRoles_Roles");

            entity.HasOne(d => d.User).WithMany(p => p.UserRoles)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserRoles_Users");
        });

        modelBuilder.Entity<ApplicationView>(entity =>
        {
            entity.HasKey(e => e.ViewId);
            entity.Property(e => e.ViewId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.ViewedAt).HasDefaultValueSql("(sysutcdatetime())");

            entity.HasOne(d => d.Application).WithMany()
                .HasForeignKey(d => d.ApplicationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ApplicationViews_Applications");

            entity.HasOne(d => d.Viewer).WithMany()
                .HasForeignKey(d => d.ViewerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ApplicationViews_Users");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}