// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UTC_DATN.Data;

#nullable disable

namespace UTC_DATN.Migrations
{
    [DbContext(typeof(UTC_DATNContext))]
    [Migration("20260210091803_AddNotificationSettingsV2")]
    partial class AddNotificationSettingsV2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JobTagMap", b =>
                {
                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("JobId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("JobTagMap", (string)null);
                });

            modelBuilder.Entity("UTC_DATN.Entities.AntiCheatEvent", b =>
                {
                    b.Property<Guid>("AntiCheatEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EventAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MetaJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AntiCheatEventId");

                    b.HasIndex(new[] { "AttemptId" }, "IX_AntiCheatEvents_AttemptId");

                    b.ToTable("AntiCheatEvents");
                });

            modelBuilder.Entity("UTC_DATN.Entities.Application", b =>
                {
                    b.Property<Guid>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("AppliedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CurrentStageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastStageChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid?>("ResumeDocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Source")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("ACTIVE");

                    b.HasKey("ApplicationId");

                    b.HasIndex("CurrentStageId");

                    b.HasIndex("ResumeDocumentId");

                    b.HasIndex(new[] { "CandidateId" }, "IX_Applications_CandidateId");

                    b.HasIndex(new[] { "JobId" }, "IX_Applications_JobId");

                    b.HasIndex(new[] { "JobId", "CandidateId" }, "UQ_Applications_Job_Candidate")
                        .IsUnique();

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("UTC_DATN.Entities.ApplicationAiScore", b =>
                {
                    b.Property<Guid>("AiScoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("MatchedSkillsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MatchingScore")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("Model")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AiScoreId");

                    b.HasIndex(new[] { "ApplicationId" }, "IX_AiScores_AppId");

                    b.ToTable("ApplicationAiScores");
                });

            modelBuilder.Entity("UTC_DATN.Entities.ApplicationNote", b =>
                {
                    b.Property<Guid>("NoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NoteId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex(new[] { "ApplicationId" }, "IX_ApplicationNotes_AppId");

                    b.ToTable("ApplicationNotes");
                });

            modelBuilder.Entity("UTC_DATN.Entities.ApplicationStageHistory", b =>
                {
                    b.Property<Guid>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FromStageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("ToStageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("HistoryId");

                    b.HasIndex("ChangedBy");

                    b.HasIndex("FromStageId");

                    b.HasIndex("ToStageId");

                    b.HasIndex(new[] { "ApplicationId" }, "IX_StageHistory_AppId");

                    b.ToTable("ApplicationStageHistory", (string)null);
                });

            modelBuilder.Entity("UTC_DATN.Entities.Assessment", b =>
                {
                    b.Property<Guid>("AssessmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DurationMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(30);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Mode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("FIXED");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("PassScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5, 2)")
                        .HasDefaultValue(60m);

                    b.Property<int?>("RandomQuestionCount")
                        .HasColumnType("int");

                    b.Property<string>("RandomTags")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("ShowResultToCandidate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("AssessmentId");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Assessments");
                });

            modelBuilder.Entity("UTC_DATN.Entities.AssessmentAnswer", b =>
                {
                    b.Property<Guid>("AnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BankQuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<decimal?>("PointsEarned")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<string>("SelectedOptionIdsJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AnswerId");

                    b.HasIndex("BankQuestionId");

                    b.HasIndex(new[] { "AttemptId" }, "IX_AssessmentAnswers_AttemptId");

                    b.ToTable("AssessmentAnswers");
                });

            modelBuilder.Entity("UTC_DATN.Entities.AssessmentAttempt", b =>
                {
                    b.Property<Guid>("AttemptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("CandidateIp")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("InviteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("Passed")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Score")
                        .HasColumnType("decimal(7, 2)");

                    b.Property<DateTime>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("IN_PROGRESS");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("AttemptId");

                    b.HasIndex(new[] { "InviteId" }, "IX_AssessmentAttempts_InviteId");

                    b.ToTable("AssessmentAttempts");
                });

            modelBuilder.Entity("UTC_DATN.Entities.AssessmentInvite", b =>
                {
                    b.Property<Guid>("InviteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SentToEmail")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("InviteId");

                    b.HasIndex("AssessmentId");

                    b.HasIndex(new[] { "ApplicationId" }, "IX_AssessmentInvites_AppId");

                    b.HasIndex(new[] { "Code" }, "UQ_AssessmentInvites_Code")
                        .IsUnique();

                    b.ToTable("AssessmentInvites");
                });

            modelBuilder.Entity("UTC_DATN.Entities.AssessmentQuestion", b =>
                {
                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BankQuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Points")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(6, 2)")
                        .HasDefaultValue(1m);

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("AssessmentId", "BankQuestionId");

                    b.HasIndex("BankQuestionId");

                    b.ToTable("AssessmentQuestions");
                });

            modelBuilder.Entity("UTC_DATN.Entities.AutomationRule", b =>
                {
                    b.Property<Guid>("RuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("ConditionJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("DelayMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TriggerEvent")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RuleId");

                    b.HasIndex("TemplateId");

                    b.ToTable("AutomationRules");
                });

            modelBuilder.Entity("UTC_DATN.Entities.Candidate", b =>
                {
                    b.Property<Guid>("CandidateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("FullName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("GitHub")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Headline")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LinkedIn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NormalizedEmail")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)")
                        .HasComputedColumnSql("(upper(ltrim(rtrim([Email]))))", true);

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Source")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CandidateId");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "NormalizedEmail" }, "IX_Candidates_NormalizedEmail");

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("UTC_DATN.Entities.CandidateDocument", b =>
                {
                    b.Property<Guid>("CandidateDocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("DocType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("CV");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ParsedJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CandidateDocumentId");

                    b.HasIndex("FileId");

                    b.HasIndex(new[] { "CandidateId" }, "IX_CandidateDocuments_CandidateId");

                    b.ToTable("CandidateDocuments");
                });

            modelBuilder.Entity("UTC_DATN.Entities.CandidateEducation", b =>
                {
                    b.Property<Guid>("EducationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Degree")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Field")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("School")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("EducationId");

                    b.HasIndex(new[] { "CandidateId" }, "IX_CandidateEducations_CandidateId");

                    b.ToTable("CandidateEducations");
                });

            modelBuilder.Entity("UTC_DATN.Entities.CandidateExperience", b =>
                {
                    b.Property<Guid>("ExperienceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Company")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ExperienceId");

                    b.HasIndex(new[] { "CandidateId" }, "IX_CandidateExperiences_CandidateId");

                    b.ToTable("CandidateExperiences");
                });

            modelBuilder.Entity("UTC_DATN.Entities.CandidateSkill", b =>
                {
                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte?>("Level")
                        .HasColumnType("tinyint");

                    b.Property<decimal?>("Years")
                        .HasColumnType("decimal(4, 1)");

                    b.HasKey("CandidateId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("CandidateSkills");
                });

            modelBuilder.Entity("UTC_DATN.Entities.ChatMessage", b =>
                {
                    b.Property<Guid>("ChatMessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("ChatSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MetaJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ChatMessageId");

                    b.HasIndex(new[] { "ChatSessionId" }, "IX_ChatMessages_SessionId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("UTC_DATN.Entities.ChatSession", b =>
                {
                    b.Property<Guid>("ChatSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("CAREER_SITE");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("ChatSessionId");

                    b.HasIndex(new[] { "ApplicationId" }, "IX_ChatSessions_AppId");

                    b.ToTable("ChatSessions");
                });

            modelBuilder.Entity("UTC_DATN.Entities.EmailQueue", b =>
                {
                    b.Property<Guid>("EmailQueueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("BodyHtml")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BodyText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("FailReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid?>("RelatedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RelatedType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ScheduledAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("QUEUED");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ToEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("ToName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("EmailQueueId");

                    b.HasIndex(new[] { "ScheduledAt" }, "IX_EmailQueue_ScheduledAt");

                    b.HasIndex(new[] { "Status" }, "IX_EmailQueue_Status");

                    b.ToTable("EmailQueue", (string)null);
                });

            modelBuilder.Entity("UTC_DATN.Entities.EmailSendLog", b =>
                {
                    b.Property<Guid>("EmailSendLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Detail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EmailQueueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("SMTP");

                    b.Property<string>("ProviderMessageId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("EmailSendLogId");

                    b.HasIndex(new[] { "EmailQueueId" }, "IX_EmailSendLog_QueueId");

                    b.ToTable("EmailSendLog", (string)null);
                });

            modelBuilder.Entity("UTC_DATN.Entities.EmailTemplate", b =>
                {
                    b.Property<Guid>("TemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("BodyHtml")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BodyText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("TemplateId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex(new[] { "Code" }, "UQ_EmailTemplates_Code")
                        .IsUnique();

                    b.ToTable("EmailTemplates");
                });

            modelBuilder.Entity("UTC_DATN.Entities.File", b =>
                {
                    b.Property<Guid>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("LocalPath")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("MimeType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("LOCAL");

                    b.Property<string>("Sha256")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("Url")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("FileId");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("UTC_DATN.Entities.Interview", b =>
                {
                    b.Property<Guid>("InterviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("InterviewerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Location")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("MeetingLink")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("ScheduledEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ScheduledStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("SCHEDULED");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("InterviewId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("InterviewerId");

                    b.HasIndex(new[] { "ApplicationId" }, "IX_Interviews_AppId");

                    b.ToTable("Interviews");
                });

            modelBuilder.Entity("UTC_DATN.Entities.InterviewEvaluation", b =>
                {
                    b.Property<Guid>("EvaluationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("InterviewId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InterviewerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("EvaluationId");

                    b.HasIndex(new[] { "InterviewId" }, "IX_InterviewEvaluations_InterviewId");

                    b.HasIndex(new[] { "InterviewerId" }, "IX_InterviewEvaluations_InterviewerId");

                    b.ToTable("InterviewEvaluations");
                });

            modelBuilder.Entity("UTC_DATN.Entities.InterviewFeedback", b =>
                {
                    b.Property<Guid>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("DetailScoresJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("InterviewId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("OverallScore")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<string>("Recommendation")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FeedbackId");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "InterviewId" }, "IX_InterviewFeedback_InterviewId");

                    b.ToTable("InterviewFeedback", (string)null);
                });

            modelBuilder.Entity("UTC_DATN.Entities.InterviewScorecard", b =>
                {
                    b.Property<Guid>("ScorecardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("CriteriaCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CriteriaName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("InterviewId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MaxScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(10);

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("ScorecardId");

                    b.HasIndex(new[] { "InterviewId" }, "IX_InterviewScorecards_InterviewId");

                    b.ToTable("InterviewScorecards");
                });

            modelBuilder.Entity("UTC_DATN.Entities.Interviewer", b =>
                {
                    b.Property<Guid>("InterviewId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RoleInPanel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("InterviewId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("Interviewers");
                });

            modelBuilder.Entity("UTC_DATN.Entities.Job", b =>
                {
                    b.Property<Guid>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Benefits")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Currency")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("VND");

                    b.Property<string>("Department")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmploymentType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("NumberOfPositions")
                        .HasColumnType("int");

                    b.Property<string>("Requirements")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SalaryMax")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("SalaryMin")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("OPEN");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("JobId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex(new[] { "Status" }, "IX_Jobs_Status");

                    b.HasIndex(new[] { "Title" }, "IX_Jobs_Title");

                    b.HasIndex(new[] { "Code" }, "UQ_Jobs_Code")
                        .IsUnique();

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("UTC_DATN.Entities.JobSkillMap", b =>
                {
                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Weight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.HasKey("JobId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("JobSkillMap", (string)null);
                });

            modelBuilder.Entity("UTC_DATN.Entities.JobTag", b =>
                {
                    b.Property<Guid>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NormalizedName")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComputedColumnSql("(upper(ltrim(rtrim([Name]))))", true);

                    b.HasKey("TagId");

                    b.HasIndex(new[] { "NormalizedName" }, "UQ_JobTags_NormalizedName")
                        .IsUnique()
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("JobTags");
                });

            modelBuilder.Entity("UTC_DATN.Entities.JobType", b =>
                {
                    b.Property<Guid>("JobTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JobTypeId");

                    b.ToTable("JobTypes");
                });

            modelBuilder.Entity("UTC_DATN.Entities.NotificationSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ChannelEmail")
                        .HasColumnType("bit");

                    b.Property<bool>("ChannelPush")
                        .HasColumnType("bit");

                    b.Property<bool>("NotifyApplicationUpdates")
                        .HasColumnType("bit");

                    b.Property<bool>("NotifyJobOpportunities")
                        .HasColumnType("bit");

                    b.Property<bool>("NotifyMarketing")
                        .HasColumnType("bit");

                    b.Property<bool>("NotifySecurityAlerts")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("NotificationSettings");
                });

            modelBuilder.Entity("UTC_DATN.Entities.PipelineStage", b =>
                {
                    b.Property<Guid>("StageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<bool>("IsTerminal")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("StageId");

                    b.HasIndex(new[] { "Code" }, "UQ_PipelineStages_Code")
                        .IsUnique();

                    b.ToTable("PipelineStages");
                });

            modelBuilder.Entity("UTC_DATN.Entities.PreScreenAnswer", b =>
                {
                    b.Property<Guid>("AnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Answer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AnswerId");

                    b.HasIndex("QuestionId");

                    b.HasIndex(new[] { "ApplicationId" }, "IX_PreScreenAnswers_AppId");

                    b.ToTable("PreScreenAnswers");
                });

            modelBuilder.Entity("UTC_DATN.Entities.PreScreenQuestion", b =>
                {
                    b.Property<Guid>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("AnswerType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("OptionsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("QuestionId");

                    b.HasIndex(new[] { "Code" }, "UQ_PreScreenQuestions_Code")
                        .IsUnique();

                    b.ToTable("PreScreenQuestions");
                });

            modelBuilder.Entity("UTC_DATN.Entities.QuestionBank", b =>
                {
                    b.Property<Guid>("BankQuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Difficulty")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Explanation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Tags")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("MCQ_SINGLE");

                    b.HasKey("BankQuestionId");

                    b.HasIndex("CreatedBy");

                    b.ToTable("QuestionBank", (string)null);
                });

            modelBuilder.Entity("UTC_DATN.Entities.QuestionOption", b =>
                {
                    b.Property<Guid>("OptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("BankQuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("OptionId");

                    b.HasIndex(new[] { "BankQuestionId" }, "IX_QuestionOptions_QId");

                    b.ToTable("QuestionOptions");
                });

            modelBuilder.Entity("UTC_DATN.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("RefreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RefreshTokenId");

                    b.HasIndex(new[] { "UserId" }, "IX_RefreshTokens_UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("UTC_DATN.Entities.Role", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RoleId");

                    b.HasIndex(new[] { "Code" }, "UQ_Roles_Code")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("UTC_DATN.Entities.Skill", b =>
                {
                    b.Property<Guid>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NormalizedName")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComputedColumnSql("(upper(ltrim(rtrim([Name]))))", true);

                    b.HasKey("SkillId");

                    b.HasIndex(new[] { "NormalizedName" }, "UQ_Skills_NormalizedName")
                        .IsUnique()
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("UTC_DATN.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("FullName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("NormalizedEmail")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)")
                        .HasComputedColumnSql("(upper(ltrim(rtrim([Email]))))", true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.HasIndex(new[] { "NormalizedEmail" }, "UQ_Users_NormalizedEmail")
                        .IsUnique()
                        .HasFilter("[NormalizedEmail] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("UTC_DATN.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("JobTagMap", b =>
                {
                    b.HasOne("UTC_DATN.Entities.Job", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .IsRequired()
                        .HasConstraintName("FK_JobTagMap_Jobs");

                    b.HasOne("UTC_DATN.Entities.JobTag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .IsRequired()
                        .HasConstraintName("FK_JobTagMap_Tags");
                });

            modelBuilder.Entity("UTC_DATN.Entities.AntiCheatEvent", b =>
                {
                    b.HasOne("UTC_DATN.Entities.AssessmentAttempt", "Attempt")
                        .WithMany("AntiCheatEvents")
                        .HasForeignKey("AttemptId")
                        .IsRequired()
                        .HasConstraintName("FK_AntiCheatEvents_Attempt");

                    b.Navigation("Attempt");
                });

            modelBuilder.Entity("UTC_DATN.Entities.Application", b =>
                {
                    b.HasOne("UTC_DATN.Entities.Candidate", "Candidate")
                        .WithMany("Applications")
                        .HasForeignKey("CandidateId")
                        .IsRequired()
                        .HasConstraintName("FK_Applications_Candidates");

                    b.HasOne("UTC_DATN.Entities.PipelineStage", "CurrentStage")
                        .WithMany("Applications")
                        .HasForeignKey("CurrentStageId")
                        .IsRequired()
                        .HasConstraintName("FK_Applications_Stage");

                    b.HasOne("UTC_DATN.Entities.Job", "Job")
                        .WithMany("Applications")
                        .HasForeignKey("JobId")
                        .IsRequired()
                        .HasConstraintName("FK_Applications_Jobs");

                    b.HasOne("UTC_DATN.Entities.CandidateDocument", "ResumeDocument")
                        .WithMany("Applications")
                        .HasForeignKey("ResumeDocumentId")
                        .HasConstraintName("FK_Applications_ResumeDoc");

                    b.Navigation("Candidate");

                    b.Navigation("CurrentStage");

                    b.Navigation("Job");

                    b.Navigation("ResumeDocument");
                });

            modelBuilder.Entity("UTC_DATN.Entities.ApplicationAiScore", b =>
                {
                    b.HasOne("UTC_DATN.Entities.Application", "Application")
                        .WithMany("ApplicationAiScores")
                        .HasForeignKey("ApplicationId")
                        .IsRequired()
                        .HasConstraintName("FK_ApplicationAiScores_App");

                    b.Navigation("Application");
                });

            modelBuilder.Entity("UTC_DATN.Entities.ApplicationNote", b =>
                {
                    b.HasOne("UTC_DATN.Entities.Application", "Application")
                        .WithMany("ApplicationNotes")
                        .HasForeignKey("ApplicationId")
                        .IsRequired()
                        .HasConstraintName("FK_ApplicationNotes_App");

                    b.HasOne("UTC_DATN.Entities.User", "CreatedByNavigation")
                        .WithMany("ApplicationNotes")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK_ApplicationNotes_User");

                    b.Navigation("Application");

                    b.Navigation("CreatedByNavigation");
                });

            modelBuilder.Entity("UTC_DATN.Entities.ApplicationStageHistory", b =>
                {
                    b.HasOne("UTC_DATN.Entities.Application", "Application")
                        .WithMany("ApplicationStageHistories")
                        .HasForeignKey("ApplicationId")
                        .IsRequired()
                        .HasConstraintName("FK_StageHistory_App");

                    b.HasOne("UTC_DATN.Entities.User", "ChangedByNavigation")
                        .WithMany("ApplicationStageHistories")
                        .HasForeignKey("ChangedBy")
                        .HasConstraintName("FK_StageHistory_User");

                    b.HasOne("UTC_DATN.Entities.PipelineStage", "FromStage")
                        .WithMany("ApplicationStageHistoryFromStages")
                        .HasForeignKey("FromStageId")
                        .HasConstraintName("FK_StageHistory_From");

                    b.HasOne("UTC_DATN.Entities.PipelineStage", "ToStage")
                        .WithMany("ApplicationStageHistoryToStages")
                        .HasForeignKey("ToStageId")
                        .IsRequired()
                        .HasConstraintName("FK_StageHistory_To");

                    b.Navigation("Application");

                    b.Navigation("ChangedByNavigation");

                    b.Navigation("FromStage");

                    b.Navigation("ToStage");
                });

            modelBuilder.Entity("UTC_DATN.Entities.Assessment", b =>
                {
                    b.HasOne("UTC_DATN.Entities.User", "CreatedByNavigation")
                        .WithMany("Assessments")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK_Assessments_User");

                    b.Navigation("CreatedByNavigation");
                });

            modelBuilder.Entity("UTC_DATN.Entities.AssessmentAnswer", b =>
                {
                    b.HasOne("UTC_DATN.Entities.AssessmentAttempt", "Attempt")
                        .WithMany("AssessmentAnswers")
                        .HasForeignKey("AttemptId")
                        .IsRequired()
                        .HasConstraintName("FK_AssessmentAnswers_Attempt");

                    b.HasOne("UTC_DATN.Entities.QuestionBank", "BankQuestion")
                        .WithMany("AssessmentAnswers")
                        .HasForeignKey("BankQuestionId")
                        .IsRequired()
                        .HasConstraintName("FK_AssessmentAnswers_Q");

                    b.Navigation("Attempt");

                    b.Navigation("BankQuestion");
                });

            modelBuilder.Entity("UTC_DATN.Entities.AssessmentAttempt", b =>
                {
                    b.HasOne("UTC_DATN.Entities.AssessmentInvite", "Invite")
                        .WithMany("AssessmentAttempts")
                        .HasForeignKey("InviteId")
                        .IsRequired()
                        .HasConstraintName("FK_AssessmentAttempts_Invite");

                    b.Navigation("Invite");
                });

            modelBuilder.Entity("UTC_DATN.Entities.AssessmentInvite", b =>
                {
                    b.HasOne("UTC_DATN.Entities.Application", "Application")
                        .WithMany("AssessmentInvites")
                        .HasForeignKey("ApplicationId")
                        .IsRequired()
                        .HasConstraintName("FK_AssessmentInvites_App");

                    b.HasOne("UTC_DATN.Entities.Assessment", "Assessment")
                        .WithMany("AssessmentInvites")
                        .HasForeignKey("AssessmentId")
                        .IsRequired()
                        .HasConstraintName("FK_AssessmentInvites_Assessment");

                    b.Navigation("Application");

                    b.Navigation("Assessment");
                });

            modelBuilder.Entity("UTC_DATN.Entities.AssessmentQuestion", b =>
                {
                    b.HasOne("UTC_DATN.Entities.Assessment", "Assessment")
                        .WithMany("AssessmentQuestions")
                        .HasForeignKey("AssessmentId")
                        .IsRequired()
                        .HasConstraintName("FK_AssessmentQuestions_A");

                    b.HasOne("UTC_DATN.Entities.QuestionBank", "BankQuestion")
                        .WithMany("AssessmentQuestions")
                        .HasForeignKey("BankQuestionId")
                        .IsRequired()
                        .HasConstraintName("FK_AssessmentQuestions_Q");

                    b.Navigation("Assessment");

                    b.Navigation("BankQuestion");
                });

            modelBuilder.Entity("UTC_DATN.Entities.AutomationRule", b =>
                {
                    b.HasOne("UTC_DATN.Entities.EmailTemplate", "Template")
                        .WithMany("AutomationRules")
                        .HasForeignKey("TemplateId")
                        .IsRequired()
                        .HasConstraintName("FK_AutomationRules_Template");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("UTC_DATN.Entities.Candidate", b =>
                {
                    b.HasOne("UTC_DATN.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UTC_DATN.Entities.CandidateDocument", b =>
                {
                    b.HasOne("UTC_DATN.Entities.Candidate", "Candidate")
                        .WithMany("CandidateDocuments")
                        .HasForeignKey("CandidateId")
                        .IsRequired()
                        .HasConstraintName("FK_CandidateDocuments_Candidates");

                    b.HasOne("UTC_DATN.Entities.File", "File")
                        .WithMany("CandidateDocuments")
                        .HasForeignKey("FileId")
                        .IsRequired()
                        .HasConstraintName("FK_CandidateDocuments_Files");

                    b.Navigation("Candidate");

                    b.Navigation("File");
                });

            modelBuilder.Entity("UTC_DATN.Entities.CandidateEducation", b =>
                {
                    b.HasOne("UTC_DATN.Entities.Candidate", "Candidate")
                        .WithMany("CandidateEducations")
                        .HasForeignKey("CandidateId")
                        .IsRequired()
                        .HasConstraintName("FK_CandidateEducations_Candidates");

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("UTC_DATN.Entities.CandidateExperience", b =>
                {
                    b.HasOne("UTC_DATN.Entities.Candidate", "Candidate")
                        .WithMany("CandidateExperiences")
                        .HasForeignKey("CandidateId")
                        .IsRequired()
                        .HasConstraintName("FK_CandidateExperiences_Candidates");

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("UTC_DATN.Entities.CandidateSkill", b =>
                {
                    b.HasOne("UTC_DATN.Entities.Candidate", "Candidate")
                        .WithMany("CandidateSkills")
                        .HasForeignKey("CandidateId")
                        .IsRequired()
                        .HasConstraintName("FK_CandidateSkills_Candidates");

                    b.HasOne("UTC_DATN.Entities.Skill", "Skill")
                        .WithMany("CandidateSkills")
                        .HasForeignKey("SkillId")
                        .IsRequired()
                        .HasConstraintName("FK_CandidateSkills_Skills");

                    b.Navigation("Candidate");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("UTC_DATN.Entities.ChatMessage", b =>
                {
                    b.HasOne("UTC_DATN.Entities.ChatSession", "ChatSession")
                        .WithMany("ChatMessages")
                        .HasForeignKey("ChatSessionId")
                        .IsRequired()
                        .HasConstraintName("FK_ChatMessages_Session");

                    b.Navigation("ChatSession");
                });

            modelBuilder.Entity("UTC_DATN.Entities.ChatSession", b =>
                {
                    b.HasOne("UTC_DATN.Entities.Application", "Application")
                        .WithMany("ChatSessions")
                        .HasForeignKey("ApplicationId")
                        .IsRequired()
                        .HasConstraintName("FK_ChatSessions_App");

                    b.Navigation("Application");
                });

            modelBuilder.Entity("UTC_DATN.Entities.EmailSendLog", b =>
                {
                    b.HasOne("UTC_DATN.Entities.EmailQueue", "EmailQueue")
                        .WithMany("EmailSendLogs")
                        .HasForeignKey("EmailQueueId")
                        .IsRequired()
                        .HasConstraintName("FK_EmailSendLog_Queue");

                    b.Navigation("EmailQueue");
                });

            modelBuilder.Entity("UTC_DATN.Entities.EmailTemplate", b =>
                {
                    b.HasOne("UTC_DATN.Entities.User", "CreatedByNavigation")
                        .WithMany("EmailTemplates")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK_EmailTemplates_User");

                    b.Navigation("CreatedByNavigation");
                });

            modelBuilder.Entity("UTC_DATN.Entities.Interview", b =>
                {
                    b.HasOne("UTC_DATN.Entities.Application", "Application")
                        .WithMany("Interviews")
                        .HasForeignKey("ApplicationId")
                        .IsRequired()
                        .HasConstraintName("FK_Interviews_App");

                    b.HasOne("UTC_DATN.Entities.User", "CreatedByNavigation")
                        .WithMany("Interviews")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK_Interviews_User");

                    b.HasOne("UTC_DATN.Entities.User", "InterviewerUser")
                        .WithMany()
                        .HasForeignKey("InterviewerId");

                    b.Navigation("Application");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("InterviewerUser");
                });

            modelBuilder.Entity("UTC_DATN.Entities.InterviewEvaluation", b =>
                {
                    b.HasOne("UTC_DATN.Entities.Interview", "Interview")
                        .WithMany()
                        .HasForeignKey("InterviewId")
                        .IsRequired()
                        .HasConstraintName("FK_InterviewEvaluations_Interview");

                    b.HasOne("UTC_DATN.Entities.User", "Interviewer")
                        .WithMany()
                        .HasForeignKey("InterviewerId")
                        .IsRequired()
                        .HasConstraintName("FK_InterviewEvaluations_Interviewer");

                    b.Navigation("Interview");

                    b.Navigation("Interviewer");
                });

            modelBuilder.Entity("UTC_DATN.Entities.InterviewFeedback", b =>
                {
                    b.HasOne("UTC_DATN.Entities.Interview", "Interview")
                        .WithMany("InterviewFeedbacks")
                        .HasForeignKey("InterviewId")
                        .IsRequired()
                        .HasConstraintName("FK_InterviewFeedback_Interview");

                    b.HasOne("UTC_DATN.Entities.User", "User")
                        .WithMany("InterviewFeedbacks")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_InterviewFeedback_User");

                    b.Navigation("Interview");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UTC_DATN.Entities.InterviewScorecard", b =>
                {
                    b.HasOne("UTC_DATN.Entities.Interview", "Interview")
                        .WithMany("InterviewScorecards")
                        .HasForeignKey("InterviewId")
                        .IsRequired()
                        .HasConstraintName("FK_InterviewScorecards_Interview");

                    b.Navigation("Interview");
                });

            modelBuilder.Entity("UTC_DATN.Entities.Interviewer", b =>
                {
                    b.HasOne("UTC_DATN.Entities.Interview", "Interview")
                        .WithMany("Interviewer")
                        .HasForeignKey("InterviewId")
                        .IsRequired()
                        .HasConstraintName("FK_Interviewers_Interview");

                    b.HasOne("UTC_DATN.Entities.User", "User")
                        .WithMany("Interviewers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Interviewers_User");

                    b.Navigation("Interview");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UTC_DATN.Entities.Job", b =>
                {
                    b.HasOne("UTC_DATN.Entities.User", "CreatedByNavigation")
                        .WithMany("Jobs")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK_Jobs_CreatedBy");

                    b.Navigation("CreatedByNavigation");
                });

            modelBuilder.Entity("UTC_DATN.Entities.JobSkillMap", b =>
                {
                    b.HasOne("UTC_DATN.Entities.Job", "Job")
                        .WithMany("JobSkillMaps")
                        .HasForeignKey("JobId")
                        .IsRequired()
                        .HasConstraintName("FK_JobSkillMap_Jobs");

                    b.HasOne("UTC_DATN.Entities.Skill", "Skill")
                        .WithMany("JobSkillMaps")
                        .HasForeignKey("SkillId")
                        .IsRequired()
                        .HasConstraintName("FK_JobSkillMap_Skills");

                    b.Navigation("Job");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("UTC_DATN.Entities.NotificationSetting", b =>
                {
                    b.HasOne("UTC_DATN.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UTC_DATN.Entities.PreScreenAnswer", b =>
                {
                    b.HasOne("UTC_DATN.Entities.Application", "Application")
                        .WithMany("PreScreenAnswers")
                        .HasForeignKey("ApplicationId")
                        .IsRequired()
                        .HasConstraintName("FK_PreScreenAnswers_App");

                    b.HasOne("UTC_DATN.Entities.PreScreenQuestion", "Question")
                        .WithMany("PreScreenAnswers")
                        .HasForeignKey("QuestionId")
                        .IsRequired()
                        .HasConstraintName("FK_PreScreenAnswers_Q");

                    b.Navigation("Application");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("UTC_DATN.Entities.QuestionBank", b =>
                {
                    b.HasOne("UTC_DATN.Entities.User", "CreatedByNavigation")
                        .WithMany("QuestionBanks")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK_QuestionBank_User");

                    b.Navigation("CreatedByNavigation");
                });

            modelBuilder.Entity("UTC_DATN.Entities.QuestionOption", b =>
                {
                    b.HasOne("UTC_DATN.Entities.QuestionBank", "BankQuestion")
                        .WithMany("QuestionOptions")
                        .HasForeignKey("BankQuestionId")
                        .IsRequired()
                        .HasConstraintName("FK_QuestionOptions_Q");

                    b.Navigation("BankQuestion");
                });

            modelBuilder.Entity("UTC_DATN.Entities.RefreshToken", b =>
                {
                    b.HasOne("UTC_DATN.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_RefreshTokens_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UTC_DATN.Entities.UserRole", b =>
                {
                    b.HasOne("UTC_DATN.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_UserRoles_Roles");

                    b.HasOne("UTC_DATN.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_UserRoles_Users");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UTC_DATN.Entities.Application", b =>
                {
                    b.Navigation("ApplicationAiScores");

                    b.Navigation("ApplicationNotes");

                    b.Navigation("ApplicationStageHistories");

                    b.Navigation("AssessmentInvites");

                    b.Navigation("ChatSessions");

                    b.Navigation("Interviews");

                    b.Navigation("PreScreenAnswers");
                });

            modelBuilder.Entity("UTC_DATN.Entities.Assessment", b =>
                {
                    b.Navigation("AssessmentInvites");

                    b.Navigation("AssessmentQuestions");
                });

            modelBuilder.Entity("UTC_DATN.Entities.AssessmentAttempt", b =>
                {
                    b.Navigation("AntiCheatEvents");

                    b.Navigation("AssessmentAnswers");
                });

            modelBuilder.Entity("UTC_DATN.Entities.AssessmentInvite", b =>
                {
                    b.Navigation("AssessmentAttempts");
                });

            modelBuilder.Entity("UTC_DATN.Entities.Candidate", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("CandidateDocuments");

                    b.Navigation("CandidateEducations");

                    b.Navigation("CandidateExperiences");

                    b.Navigation("CandidateSkills");
                });

            modelBuilder.Entity("UTC_DATN.Entities.CandidateDocument", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("UTC_DATN.Entities.ChatSession", b =>
                {
                    b.Navigation("ChatMessages");
                });

            modelBuilder.Entity("UTC_DATN.Entities.EmailQueue", b =>
                {
                    b.Navigation("EmailSendLogs");
                });

            modelBuilder.Entity("UTC_DATN.Entities.EmailTemplate", b =>
                {
                    b.Navigation("AutomationRules");
                });

            modelBuilder.Entity("UTC_DATN.Entities.File", b =>
                {
                    b.Navigation("CandidateDocuments");
                });

            modelBuilder.Entity("UTC_DATN.Entities.Interview", b =>
                {
                    b.Navigation("InterviewFeedbacks");

                    b.Navigation("InterviewScorecards");

                    b.Navigation("Interviewer");
                });

            modelBuilder.Entity("UTC_DATN.Entities.Job", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("JobSkillMaps");
                });

            modelBuilder.Entity("UTC_DATN.Entities.PipelineStage", b =>
                {
                    b.Navigation("ApplicationStageHistoryFromStages");

                    b.Navigation("ApplicationStageHistoryToStages");

                    b.Navigation("Applications");
                });

            modelBuilder.Entity("UTC_DATN.Entities.PreScreenQuestion", b =>
                {
                    b.Navigation("PreScreenAnswers");
                });

            modelBuilder.Entity("UTC_DATN.Entities.QuestionBank", b =>
                {
                    b.Navigation("AssessmentAnswers");

                    b.Navigation("AssessmentQuestions");

                    b.Navigation("QuestionOptions");
                });

            modelBuilder.Entity("UTC_DATN.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("UTC_DATN.Entities.Skill", b =>
                {
                    b.Navigation("CandidateSkills");

                    b.Navigation("JobSkillMaps");
                });

            modelBuilder.Entity("UTC_DATN.Entities.User", b =>
                {
                    b.Navigation("ApplicationNotes");

                    b.Navigation("ApplicationStageHistories");

                    b.Navigation("Assessments");

                    b.Navigation("EmailTemplates");

                    b.Navigation("InterviewFeedbacks");

                    b.Navigation("Interviewers");

                    b.Navigation("Interviews");

                    b.Navigation("Jobs");

                    b.Navigation("QuestionBanks");

                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
