// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UTC_DATN.Entities;

public partial class Application
{
    public Guid ApplicationId { get; set; }

    public Guid JobId { get; set; }

    public Guid CandidateId { get; set; }

    public Guid CurrentStageId { get; set; }

    public DateTime AppliedAt { get; set; }

    public DateTime LastStageChangedAt { get; set; }

    public Guid? ResumeDocumentId { get; set; }

    public string Source { get; set; }

    public string Status { get; set; }

    /// <summary>
    /// Snapshot email liên lạc tại thời điểm nộp hồ sơ (Historical Data Integrity)
    /// </summary>
    public string? ContactEmail { get; set; }

    /// <summary>
    /// Snapshot số điện thoại tại thời điểm nộp hồ sơ (Historical Data Integrity)
    /// </summary>
    public string? ContactPhone { get; set; }

    public virtual ICollection<ApplicationAiScore> ApplicationAiScores { get; set; } = new List<ApplicationAiScore>();

    public virtual ICollection<ApplicationNote> ApplicationNotes { get; set; } = new List<ApplicationNote>();

    public virtual ICollection<ApplicationStageHistory> ApplicationStageHistories { get; set; } = new List<ApplicationStageHistory>();

    public virtual ICollection<AssessmentInvite> AssessmentInvites { get; set; } = new List<AssessmentInvite>();

    public virtual Candidate Candidate { get; set; }

    public virtual ICollection<ChatSession> ChatSessions { get; set; } = new List<ChatSession>();

    public virtual PipelineStage CurrentStage { get; set; }

    public virtual ICollection<Interview> Interviews { get; set; } = new List<Interview>();

    public virtual Job Job { get; set; }

    public virtual ICollection<PreScreenAnswer> PreScreenAnswers { get; set; } = new List<PreScreenAnswer>();

    public virtual CandidateDocument ResumeDocument { get; set; }
}