// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UTC_DATN.Entities;

public partial class CandidateDocument
{
    public Guid CandidateDocumentId { get; set; }

    public Guid CandidateId { get; set; }

    public Guid FileId { get; set; }

    public string DocType { get; set; }

    public string ParsedJson { get; set; }

    public bool IsPrimary { get; set; }

    public string DisplayName { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<Application> Applications { get; set; } = new List<Application>();

    public virtual Candidate Candidate { get; set; }

    public virtual File File { get; set; }
}