// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UTC_DATN.Entities;

public partial class Candidate
{
    public Guid CandidateId { get; set; }

    public string Email { get; set; }

    public string NormalizedEmail { get; set; }

    public string FullName { get; set; }

    public string Phone { get; set; }

    public string Location { get; set; }

    public string Headline { get; set; }

    public string Summary { get; set; }

    public string Source { get; set; }

    public string? LinkedIn { get; set; }

    public string? GitHub { get; set; }

    public string? Avatar { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public bool IsDeleted { get; set; }

    // Liên kết với User (nullable - cho phép apply không cần đăng nhập)
    public Guid? UserId { get; set; }

    public virtual User User { get; set; }

    public virtual ICollection<Application> Applications { get; set; } = new List<Application>();

    public virtual ICollection<CandidateDocument> CandidateDocuments { get; set; } = new List<CandidateDocument>();

    public virtual ICollection<CandidateEducation> CandidateEducations { get; set; } = new List<CandidateEducation>();

    public virtual ICollection<CandidateExperience> CandidateExperiences { get; set; } = new List<CandidateExperience>();

    public virtual ICollection<CandidateSkill> CandidateSkills { get; set; } = new List<CandidateSkill>();
}