// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UTC_DATN.Entities;

public partial class Job
{
    public Guid JobId { get; set; }

    public string Code { get; set; }

    public string Title { get; set; }

    public string Department { get; set; }

    public string Location { get; set; }

    public string EmploymentType { get; set; }

    public decimal? SalaryMin { get; set; }

    public decimal? SalaryMax { get; set; }

    public string Currency { get; set; }

    public string Description { get; set; }

    public string Requirements { get; set; }

    public string Benefits { get; set; }

    public int? NumberOfPositions { get; set; }

    public string Status { get; set; }

    public Guid? CreatedBy { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? ClosedAt { get; set; }

    public DateTime? Deadline { get; set; }

    public bool IsDeleted { get; set; }

    public virtual ICollection<Application> Applications { get; set; } = new List<Application>();

    public virtual User CreatedByNavigation { get; set; }

    public virtual ICollection<JobSkillMap> JobSkillMaps { get; set; } = new List<JobSkillMap>();

    public virtual ICollection<JobTag> Tags { get; set; } = new List<JobTag>();
}