// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UTC_DATN.Entities;

public partial class PipelineStage
{
    public Guid StageId { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    public int SortOrder { get; set; }

    public bool IsTerminal { get; set; }

    public DateTime CreatedAt { get; set; }

    public int? SlaMaxDays { get; set; }

    public int? SlaWarnBeforeDays { get; set; }

    public bool? IsSlaEnabled { get; set; }

    public virtual ICollection<ApplicationStageHistory> ApplicationStageHistoryFromStages { get; set; } = new List<ApplicationStageHistory>();

    public virtual ICollection<ApplicationStageHistory> ApplicationStageHistoryToStages { get; set; } = new List<ApplicationStageHistory>();

    public virtual ICollection<Application> Applications { get; set; } = new List<Application>();
}