// <auto-generated> This file has been added manually </auto-generated>
#nullable disable
using System;

namespace UTC_DATN.Entities;

public partial class SavedJob
{
    public Guid SavedJobId { get; set; }

    public Guid CandidateId { get; set; }

    public Guid JobId { get; set; }

    public DateTime SavedAt { get; set; }

    public virtual Candidate Candidate { get; set; }

    public virtual Job Job { get; set; }
}
