// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UTC_DATN.Entities;

public partial class User
{
    public Guid UserId { get; set; }

    public string Email { get; set; }

    public string NormalizedEmail { get; set; }

    public string PasswordHash { get; set; }

    public string FullName { get; set; }

    public string Phone { get; set; }

    public string AvatarUrl { get; set; }

    public bool IsActive { get; set; }

    public string AuthProvider { get; set; } = "Local";

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    // Audit Trail: Ai đã khóa tài khoản này?
    public DateTime? LockedAt { get; set; }
    public Guid? LockedById { get; set; }
    public string LockedByName { get; set; }
    public string LockReason { get; set; }

    // Company Information
    public string CompanyName { get; set; }
    public string CompanyWebsite { get; set; }
    public string CompanyIndustry { get; set; }
    public string CompanyAddress { get; set; }
    public string CompanyDescription { get; set; }
    public string CompanyLogoUrl { get; set; }

    public virtual ICollection<ApplicationNote> ApplicationNotes { get; set; } = new List<ApplicationNote>();

    public virtual ICollection<ApplicationStageHistory> ApplicationStageHistories { get; set; } = new List<ApplicationStageHistory>();

    public virtual ICollection<Assessment> Assessments { get; set; } = new List<Assessment>();

    public virtual ICollection<EmailTemplate> EmailTemplates { get; set; } = new List<EmailTemplate>();

    public virtual ICollection<InterviewFeedback> InterviewFeedbacks { get; set; } = new List<InterviewFeedback>();

    public virtual ICollection<Interviewer> Interviewers { get; set; } = new List<Interviewer>();

    public virtual ICollection<Interview> Interviews { get; set; } = new List<Interview>();

    public virtual ICollection<Job> Jobs { get; set; } = new List<Job>();

    public virtual ICollection<QuestionBank> QuestionBanks { get; set; } = new List<QuestionBank>();

    public virtual ICollection<RefreshToken> RefreshTokens { get; set; } = new List<RefreshToken>();

    public virtual ICollection<UserRole> UserRoles { get; set; } = new List<UserRole>();
}